# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
inhibit_all_warnings!

target 'ImagePickerController' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ImagePickerController
  
   pod 'Masonry'

   pod 'TZImagePickerController'

end
